name: Main Workflow

on:
  pull_request:
    types: [closed]

jobs:
  login_build_push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Pulling code
        uses: actions/checkout@v3

      - name: login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pushing to dockerhub
        run: |
          docker build -t mu5a/docker-node-hello-world .
          docker push mu5a/docker-node-hello-world:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: pushing to github container registry
        run: |
          docker build . --tag ghcr.io/mu5a/docker-node-hello-world:latest
          docker push ghcr.io/mu5a/docker-node-hello-world:latest

      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ECR_REGISTRY }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: pushing into ECR
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/docker-node-hello-world:latest .
          docker push ${{ secrets.ECR_REGISTRY }}/docker-node-hello-world:latest
